// <auto-generated />
namespace ProjetoInicio.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class mori1479 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mori1479));
        
        string IMigrationMetadata.Id
        {
            get { return "201907301708354_mori1479"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
